locators = {
    'Логин': '[data-test="login-field"]',
    'Пароль': '[data-test="password-field"]',
    'Поле ввода': '[data-test="text-field"]',
    'Проверочное поле': '[data-test="test-text"]',
    'Кнопка': '[data-test="normal-button"]',
    'Неактивная кнопка': '[data-test="disabled-button"]',
    'Скрытая кнопка': '[data-test="hidden-button"]',
    'Показать': '[data-test="checkbox-label"]',
    'Чекбокс': '[data-test="checkbox"]',
    'Фильтр': '[data-test="filter"]',
    'Список': '[data-test="filtered-items"] > *',
    'Контейнер': '[data-test="scrollable-container"]',
    'Элементы': '[data-test="scrollable-container"] > *',
    'Проверочное поле списка': '[data-test="test-item"]',
    'Логотип ZAPP': '[class^="header-logo"]',
    'Картинка': '[data-test="hover-animation"]',
    'Фрейм': '[data-test="iframe"]',
    'Поле ввода во фрейме': '[data-test="iframe-text-field"]',
    'Проверочное поле во фрейме': '[data-test="iframe-test-text"]',
    'Скачивание файла': '[data-test="download-link"]',
    'Загрузка файла': '[data-test="upload-input"]',
    'Сохранить': '[data-test="submit-button"]',
    'ZAPP DLC': 'https://zapp.example.com/manual#dlc',
    'Логотип ZAPP во фрейме': '[alt="ZAPP"]',

}
